Algoritmo "L01A"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 
    C, F: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite a temperatua em Celsius: ")
leia(C)
F <- (9 * C + 160) / 5
escreva("Fahrenheit: ", F)

Fimalgoritmo