Algoritmo "L01C"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 
raio, altura, volume: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite o raio: ")
leia (raio)
Escreva("Digite a altura: ")
leia(altura)
volume <- 3.1416 * raio * raio * altura
Escreval("Volume: ", volume)

Fimalgoritmo