Algoritmo "L01H"
// Disciplina   : [ Lógica de Programação]
// Professor   : jaja
// Descrição   : Elaborar um programa que calcule e apresente o volume de uma caixa retangular, por meio da fórmula
//VOLUME  COMPRIMENTO * LARGURA * ALTURA.
// Autor(a)    : Larissa
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 
comp, larg, alt, volume: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Comprimento")
leia(comp)
escreva("Largura")
leia(Larg)
escreva("Altura")
leia(alt)
volume <- comp * larg * alt
escreva("Volume: ", volume)

Fimalgoritmo