Algoritmo "L01L"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Elaborar um programa que efetue a leitura de três valores (A, B e C) e apresente como resultado final à
//soma dos quadrados dos três valores lidos
// Autor(a)    : Larissa
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis
A,B,C,resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Valor da A")
leia(A)
escreva("Valor da B")
leia(B)
escreva("Valor da C")
leia(C)
resultado <- (A*A) + (B*B) + (C*C)
escreva("Resultado: ", resultado)

fimalgoritmo