Algoritmo "L02G"
// Disciplina   : [Lógica de Programação]
// Professor    : Jailson
// Descrição   :Efetuar a leitura de quatro números inteiros e apresentar os números que são divisíveis por 2 e 3
// Autor(a)    : Larissa
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 
a,b,c,d: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("digite A")
leia(a)
escreva ("digite B")
leia(b)
escreva ("digite C")
leia(c)
escreva ("digite D")
leia(d)
   se a mod 2 = 0 e a mod 3 = 0 entao escreval(a) fimse
   se b mod 2 = 0 e b mod 3 = 0 entao escreval(b) fimse
   se c mod 2 = 0 e c mod 3 = 0 entao escreval(c) fimse
   se d mod 2 = 0 e d mod 3 = 0 entao escreval(d) fimse
   escreval("Números divisíveis por 2 e 3:")


Fimalgoritmo