Algoritmo "L02K"
// Disciplina   : [Lógica de Programação]
// Professor    : Jailson
// Descrição   :lElaborar um programa que efetue a leitura de um determinado valor inteiro, e efetue a sua
//apresentação, caso o valor não seja maior que três
// Autor(a)    : Larissa
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("número:")
leia(num)
    se num <= 3 entao
      escreval(num)
   fimse

Fimalgoritmo