Algoritmo "L03A"
// Disciplina  : [LLógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : LArissa Inês
// Data atual  : 20/04/2026
var
   num, i, resultado: inteiro
inicio
escreva("Digite um numero: ")
leia(num)
i <- 1
enquanto i <= 10 faca
resultado <- num * i
escreval(num, " x ", i, " = ", resultado)
    i <- i + 1
fimenquanto
Fimalgoritmo