Algoritmo "L03D"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Larissa Inês
// Data atual  : 20/04/2026
Var
// Seção de Declarações das variáveis 
 i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("--- NUMEROS IMPARES DE 0 A 20 ---")
i <- 0
enquanto i <= 20 faca
se i mod 2 <> 0 entao
     escreval("Impar: ", i)
   fimse
   i <- i + 1
  fimenquanto

Fimalgoritmo