Algoritmo "L03H"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Elaborar um programa que apresente os valores de conversão de graus Celsius em Fahrenhei
// Autor(a)    : Larissa Inês
// Data atual  : 20/04/2026
Var
// Seção de Declarações das variáveis 
c, f: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("--- CELSIUS PARA FAHRENHEIT ---")
  c <- 10
enquanto c <= 100 faca
  f <- (9 * c + 160) / 5
escreval("C: ", c, " -> F: ", f)
   c <- c + 10
   fimenquanto

Fimalgoritmo